[platformio]
default_envs = m5stack-core2

[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino
lib_deps =
    m5stack/M5Unified@^0.2.2
    bblanchon/ArduinoJson@^7.4.1
monitor_speed = 115200
build_flags =
    -std=gnu++17
    -DENABLE_WIFI_SCAN=1
    -DCORE_DEBUG_LEVEL=1
build_unflags = -std=gnu++11

[env:native]
platform = native
build_flags = -std=c++17
test_filter = test_native
lib_deps =
